# Statistics {#statistics}

## `Statistics` trait

* To make generic code, there is `Statistics` trait
    * `mean`: just mean
    * `var` : variance
    * `sd` : standard deviation (R-like notation)
    * `cov` : covariance
    * `cor` : correlation coefficient
    ```rust
    pub trait Statistics {
        type Array;
        type Value;

        fn mean(&self) -> Self::Value;
        fn var(&self) -> Self::Value;
        fn sd(&self) -> Self::Value;
        fn cov(&self) -> Self::Array;
        fn cor(&self) -> Self::Array;
    }
    ```

### For `Vec<f64>`

* Caution: For `Vec<f64>`, `cov` & `cor` are unimplemented (those for `Matrix`)

    ```rust
    fn main() {
        let a = c!(1,2,3,4,5);
        a.mean().print(); // 3
        a.var().print();  // 2.5
        a.sd().print();   // 1.5811388300841898
    }
    ```

* But there are other functions to calculate `cov` & `cor`

    ```rust
    fn main() {
        let v1 = c!(1,2,3);
        let v2 = c!(3,2,1);

        cov(&v1, &v2).print(); // -0.9999999999999998
        cor(&v1, &v2).print(); // -0.9999999999999993
    }
    ```

### For `Matrix`

* For `Matrix`, `mean, var, sd` means column operations
* `cov` means covariance matrix & `cor` means also correlation coefficient matrix

    ```rust
    fn main() {
        let m = matrix(c!(1,2,3,3,2,1), 3, 2, Col);
        
        m.mean().print(); // [2, 2]
        m.var().print();  // [1.0000, 1.0000]
        m.sd().print();   // [1.0000, 1.0000]

        m.cov().print();
        //         c[0]    c[1]
        // r[0]  1.0000 -1.0000
        // r[1] -1.0000  1.0000
        
        m.cor().print();
        //         c[0]    c[1]
        // r[0]       1 -1.0000
        // r[1] -1.0000       1
    }
    ```

## Simple Random Number Generator

* Peroxide uses external [`rand` crate](https://crates.io/crates/rand) to generate random number

    ```rust
    extern crate rand;
    use self::rand::prelude::*;
    
    fn main() {
        let mut rng = thread_rng();

        let a = rng.gen_range(0f64, 1f64); // Generate random f64 number ranges from 0 to 1
    }
    ```

* To want more detailed explanation, see [`rand` crate](https://crates.io/crates/rand)

## Probability Distribution

* There are some famous pdf in Peroxide (not checked pdfs will be implemented soon)
    * [x] Bernoulli
    * [x] Beta
    * [ ] Dirichlet
    * [x] Gamma
    * [x] Normal
    * [ ] Student's t
    * [x] Uniform
    * [ ] Wishart
* There are two enums to represent probability distribution
    * `OPDist<T>` : One parameter distribution (Bernoulli)
    * `TPDist<T>` : Two parameter distribution (Uniform, Normal, Beta, Gamma)
        * `T: PartialOrd + SampleUniform + Copy + Into<f64>` 
* There are some traits for pdf
    * `RNG` trait - extract sample & calculate pdf
    * `Statistics` trait - already shown above

### `RNG` trait

* `RNG` trait is composed of two fields
    * `sample`: Extract samples
    * `pdf` : Calculate pdf value at specific point
    ```rust
    pub trait RNG {
        /// Extract samples of distributions
        fn sample(&self, n: usize) -> Vec<f64>;

        /// Probability Distribution Function
        ///
        /// # Type
        /// `f64 -> f64`
        fn pdf<S: PartialOrd + SampleUniform + Copy + Into<f64>>(&self, x: S) -> f64;
    }
    ```

### Bernoulli Distribution

* Definition
    $$\text{Bern}(x | \mu) = \mu^x (1-\mu)^{1-x}$$
* Representative value
    * Mean: $\mu$
    * Var : $\mu(1 - \mu)$
* In peroxide, to generate $\text{Bern}(x | \mu)$, use simple algorithm
    1. Generate $U \sim \text{Unif}(0, 1)$
    2. If $U \leq \mu$, then $X = 1$ else $X = 0$
* Usage is very simple

    ```rust
    fn main() {
        let b = Bernoulli(0.1); // Bern(x | 0.1)
        b.sample(100).print();  // Generate 100 samples
        b.pdf(0).print();       // 0.9
        b.mean().print();       // 0.1
        b.var().print();        // 0.09 (approximately)
        b.sd().print();         // 0.3  (approximately)
    }
    ```

### Uniform Distribution

* Definition
    $$\text{Unif}(x | a, b) = \begin{cases}
     \frac{1}{b - a} & x \in [a,b]\\
     0 & \text{otherwise}
    \end{cases}$$
* Representative value
    * Mean: $\frac{a + b}{2}$
    * Var : $\frac{1}{12}(b-a)^2$
* To generate uniform random number, Peroxide uses `rand` crate

    ```rust
    fn main() {
        let a = Unif(0, 1);
        a.sample(100).print();
        a.pdf(0.2).print();
        a.mean().print();
        a.var().print();
        a.sd().print();
    }
    ```

### Normal Distribution

### Beta Distribution

### Gamma Distribution